### ISSUE TITLE
Reload button

### ISSUE THREAD

**Issue by 97gamjak** [MolarVerse/PQEnalyzer#31]
It would be really nice to have a reload button - so the user would not have to make an other plot if he for example adds a new statistic object to the plot.

**Comment by galjos** [comment]
Will be included in #32. But, something strange is happening. The axis is not clear properly and I need someone to test it on a running simulation, because the live plotting feature is dependent on the refresh/reload now. 

So, @97gamjak if you would be so kind and test the the branch of #32.

In theory it should work. All functions that are called are entered correctly.

**Comment by 97gamjak** [comment]
So basically my task is to test the general plotting feature for a running simulation, as this would somehow mimic the behaviour of the replot button? Did I get this right?

**Comment by galjos** [comment]
Please test both buttons

**Comment by galjos** [comment]
Sorry, the follow checkbox and the refresh button

**Comment by 97gamjak** [comment]
> Sorry, the follow checkbox and the refresh button

Will be done by tomorrow evening!
